version: "3.1"

volumes:
  postgres-data: {}

services:
  sme-db:
    container_name: sme-db
    restart: always
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  sme-redis:
    image: redis:5.0.5-alpine
    container_name: sme-redis
    ports:
      - "6379:6379"
  sme-flyway:
    container_name: sme-flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://sme-db:5432/sgp_db?user=postgres&password=postgres -locations='filesystem:/opt/scripts' -outOfOrder=true migrate
    volumes:
      - ./scripts:/opt/scripts
    depends_on:
      - sme-db
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine
    networks:
      - default
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: bitnami
    ports:
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
