version: "3.1"

volumes:
  grafana_data: {}
  postgres-data: {}

services:
  sme-api:
    container_name: sme-api
    image: sme-api
    build:
      context: .
      dockerfile: ./src/SME.SGP.Api/Dockerfile
    ports:
      - "20000:80"
    networks:
      - sme-network
    depends_on:
      - "postgres"
  postgres:
    container_name: sme-sgp_db
    restart: always
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sme-network
  grafana:
    container_name: sme-grafana
    restart: always
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - grafana_data:/var/lib/grafana
    networks:
      - sme-network
    depends_on:
      - "prom"
  prom:
    container_name: sme-prometheus
    image: sme-prometheus
    build:
      context: .
      dockerfile: ./prometheus/Dockerfile
    ports:
      - 9090:9090
    networks:
      - sme-network
    depends_on:
      - "sme-api"
networks:
  sme-network:
    driver: bridge
